In [2]:
# Import our dependencies
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
# Read in our dataset
hr_df = pd.read_csv("Resources/hr_dataset.csv")
hr_df

    Satisfaction_Level  Num_Projects  Time_Spent  Num_Promotions
0                 0.30             1         253               2
1                 0.25             1         200               0
2                 0.90             4        2880               5
3                 0.65             3        1450               3
4                 0.50             2         785               2
5                 0.40             2         688               2
6                 0.85             4        2570               4
7                 0.90             5        2956               4
8                 0.15             0          68               1
9                 1.00             5        3424               6
10                0.70             3        2057               3
11                0.23             1         362               1
12                0.48             1         572               2
13                0.41             2         526               2
14                0.55             3         682               2
15                0.70             4        1575               4
16                0.65             3        1480               3
17                0.80             4        2390               4
18                0.87             4        2855               5
19                0.38             2         523               1
20                0.60             2        1025               2
21                0.90             5        3259               5
22                1.00             6        4816               7
23                0.75             3        1269               3
24                0.80             3        1540               3
25                0.46             1         605               2
26                0.50             2         832               2
27                0.35             1         428               1
28                0.70             2        1015               3

In [9]:
# Make sure to do one-hot encoding if there are categorical variables first

# Create the StandardScaler instance
scaled_data = StandardScaler().fit_transform(hr_df)

# Make dataframe from scaled data
scaled_df = pd.DataFrame(scaled_data, columns = hr_df.columns)
scaled_df

    Satisfaction_Level  Num_Projects  Time_Spent  Num_Promotions
0            -1.303615     -1.162476   -1.049481       -0.558656
1            -1.512945     -1.162476   -1.094603       -1.804887
2             1.208335      0.860233    1.187080        1.310692
3             0.161689      0.185996   -0.030385        0.064460
4            -0.466299     -0.488240   -0.596549       -0.558656
5            -0.884957     -0.488240   -0.679133       -0.558656
6             0.999005      0.860233    0.923154        0.687576
7             1.208335      1.534469    1.251785        0.687576
8            -1.931603     -1.836713   -1.206985       -1.181771
9             1.626993      1.534469    1.650228        1.933808
10            0.371018      0.185996    0.486399        0.064460
11           -1.596676     -1.162476   -0.956681       -1.181771
12           -0.550030     -1.162476   -0.777892       -0.558656
13           -0.843091     -0.488240   -0.817055       -0.558656
14           -0.256970      0.185996   -0.684241       -0.558656
15            0.371018      0.860233    0.076037        0.687576
16            0.161689      0.185996   -0.004844        0.064460
17            0.789676      0.860233    0.769907        0.687576
18            1.082737      0.860233    1.165796        1.310692
19           -0.968689     -0.488240   -0.819609       -1.181771
20           -0.047640     -0.488240   -0.392219       -0.558656
21            1.208335      1.534469    1.509751        1.310692
22            1.626993      2.208705    2.835341        2.556924
23            0.580347      0.185996   -0.184484        0.064460
24            0.789676      0.185996    0.046238        0.064460
25           -0.633762     -1.162476   -0.749797       -0.558656
26           -0.466299     -0.488240   -0.556535       -0.558656
27           -1.094286     -1.162476   -0.900490       -1.181771
28            0.371018     -0.488240   -0.400733        0.064460

In [14]:
# Checking to make sure mean is about 0 and SD is 1
scaled_df.describe()

       Satisfaction_Level  Num_Projects    Time_Spent  Num_Promotions
count        2.900000e+01  2.900000e+01  2.900000e+01    2.900000e+01
mean        -1.473917e-16  7.082457e-17  4.211191e-17   -2.871266e-18
std          1.017700e+00  1.017700e+00  1.017700e+00    1.017700e+00
min         -1.931603e+00 -1.836713e+00 -1.206985e+00   -1.804887e+00
25%         -8.430912e-01 -4.882401e-01 -7.778921e-01   -5.586556e-01
50%          1.616887e-01  1.859962e-01 -3.922194e-01    6.446026e-02
75%          7.896762e-01  8.602325e-01  7.699067e-01    6.875761e-01
max          1.626993e+00  2.208705e+00  2.835341e+00    2.556924e+00