In [1]:
# SVMs are a type of binary classifier that use geometric boundaries to distinguish data points from two separate groups. 
# More specifically, SVMs try to calculate a geometric hyperplane that maximizes the distance between the closest data point of both groups:

# Unlike logistic regression, which excels in classifying data that is linearly separable but fails in nonlinear relationships, SVMs can build adequate models with linear or nonlinear data
# Due to SVMs' ability to create multidimensional borders, SVMs lose their interpretability and behave more like the black box machine learning models, such as basic neural networks and deep learning models.
# SVMs, like neural networks, can analyze and interpret multiple data types, such as images, natural language voice and text, or tabular data.

# SVMs perform one task and one task very well—they classify and create regression using two groups.
# In contrast, neural networks and deep learning models are capable of producing many outputs, which means neural network models can be used to classify multiple groups within the same model.

# If we only compare binary classification problems, SVMs have an advantage over neural network and deep learning models:
# - Neural networks and deep learning models will often converge on a local minimum. In other words, these models will often focus on a specific trend in the data and could miss the "bigger picture."
# - SVMs are less prone to overfitting because they are trying to maximize the distance, rather than encompass all data within a boundary.
# - Despite these advantages, SVMs are limited in their potential and can still miss critical features and high-dimensionality relationships that a well-trained deep learning model could find. 
# - However, in many straightforward binary classification problems, SVMs will outperform the basic neural network, and even deep learning models with ease.

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf

In [3]:
# Import our input dataset
tele_df = pd.read_csv('Resources/bank_telemarketing.csv')
tele_df

,Age,Job,Marital_Status,Education,Default_Credit,Housing_Loan,Personal_Loan,Subscribed
0,56,other,married,Primary_Education,no,no,no,no
1,37,services,married,Secondary_Education,no,yes,no,no
2,40,admin,married,Primary_Education,no,no,no,no
3,56,services,married,Secondary_Education,no,no,yes,no
4,59,admin,married,Professional_Education,no,no,no,no
...,...,...,...,...,...,...,...,...
30472,73,retired,married,Professional_Education,no,yes,no,yes
30473,46,blue-collar,married,Professional_Education,no,no,no,no
30474,56,retired,married,Tertiary_Education,no,yes,no,no
30475,44,technician,married,Professional_Education,no,no,no,yes
30476,74,retired,married,Professional_Education,no,yes,no,no

In [15]:
# encode categorical variables with one-hot encoder

# generate categorical variable list
cat_vars = tele_df.dtypes[tele_df.dtypes==object].index.tolist()
cat_vars

# Check the number of unique values in each column to make sure they're under 10 and don't need bucketing
tele_df[cat_vars].nunique()

Job               9
Marital_Status    3
Education         4
Default_Credit    2
Housing_Loan      2
Personal_Loan     2
Subscribed        2
dtype: int64

In [18]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(tele_df[cat_vars]))
encode_df.columns = enc.get_feature_names_out(cat_vars)
encode_df

,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,Marital_Status_divorced,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30472,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
30473,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
30474,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
30475,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
30476,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [19]:
# Add encoded variables back to original dataframe
combined_df = tele_df.join(encode_df).drop(columns = cat_vars)
combined_df

,Age,Job_admin,Job_blue-collar,Job_entrepreneur,Job_management,Job_other,Job_retired,Job_self-employed,Job_services,Job_technician,...,Education_Secondary_Education,Education_Tertiary_Education,Default_Credit_no,Default_Credit_yes,Housing_Loan_no,Housing_Loan_yes,Personal_Loan_no,Personal_Loan_yes,Subscribed_no,Subscribed_yes
0,56,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,40,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
4,59,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30472,73,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
30473,46,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
30474,56,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
30475,44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
30476,74,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [24]:
# split data into the training and testing sets prior to standardization to not incorporate the testing values into the scale—testing values are only for evaluation

y = combined_df["Subscribed_yes"].values
X = combined_df.drop(columns=["Subscribed_yes", "Subscribed_no"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [25]:
# use the SVM's linear kernel to try and create a linear boundary between the "Subscribed_yes" versus "Subscribed_no" groups

# Create the SVM model
svm = SVC(kernel="linear")

# Train the model
svm.fit(X_train_scaled, y_train)

# Evaluate the model
predictions = svm.predict(X_test_scaled)
print(f" SVM model accuracy: {accuracy_score(y_test,predictions):.3f}")

 SVM model accuracy: 0.873

In [26]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

WARNING:tensorflow:From /Users/emarieswenson/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

WARNING:tensorflow:From /Users/emarieswenson/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

WARNING:tensorflow:From /Users/emarieswenson/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

WARNING:tensorflow:From /Users/emarieswenson/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [27]:
# Because this dataset contains fewer features than other datasets we have used previously, we only need to train over a maximum of 50 epochs

# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=50) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Train on 22857 samples
Epoch 1/50

2022-09-05 11:37:21.148443: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-05 11:37:21.150288: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.

22857/22857 [==============================] - 1s 43us/sample - loss: 0.4428 - acc: 0.8307
Epoch 2/50
22857/22857 [==============================] - 1s 31us/sample - loss: 0.3753 - acc: 0.8730
Epoch 3/50
22857/22857 [==============================] - 1s 30us/sample - loss: 0.3720 - acc: 0.8733
Epoch 4/50
22857/22857 [==============================] - 1s 30us/sample - loss: 0.3705 - acc: 0.8735
Epoch 5/50
22857/22857 [==============================] - 1s 30us/sample - loss: 0.3692 - acc: 0.8736
Epoch 6/50
22857/22857 [==============================] - 1s 30us/sample - loss: 0.3680 - acc: 0.8734
Epoch 7/50
22857/22857 [==============================] - 1s 30us/sample - loss: 0.3667 - acc: 0.8735
Epoch 8/50
22857/22857 [==============================] - 1s 31us/sample - loss: 0.3664 - acc: 0.8735
Epoch 9/50
22857/22857 [==============================] - 1s 30us/sample - loss: 0.3658 - acc: 0.8734
Epoch 10/50
22857/22857 [==============================] - 1s 31us/sample - loss: 0.3652 - acc: 0.8736
Epoch 11/50
22857/22857 [==============================] - 1s 31us/sample - loss: 0.3646 - acc: 0.8736
Epoch 12/50
22857/22857 [==============================] - 1s 31us/sample - loss: 0.3645 - acc: 0.8734
Epoch 13/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3640 - acc: 0.8739
Epoch 14/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3637 - acc: 0.8735
Epoch 15/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3637 - acc: 0.8735
Epoch 16/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3634 - acc: 0.8731
Epoch 17/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3632 - acc: 0.8733
Epoch 18/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3633 - acc: 0.8735
Epoch 19/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3631 - acc: 0.8736
Epoch 20/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3629 - acc: 0.8732
Epoch 21/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3627 - acc: 0.8736
Epoch 22/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3625 - acc: 0.8734
Epoch 23/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3625 - acc: 0.8733
Epoch 24/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3622 - acc: 0.8735
Epoch 25/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3624 - acc: 0.8735
Epoch 26/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3621 - acc: 0.8737
Epoch 27/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3623 - acc: 0.8736
Epoch 28/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3618 - acc: 0.8736
Epoch 29/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3620 - acc: 0.8737
Epoch 30/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3619 - acc: 0.8733
Epoch 31/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3619 - acc: 0.8738
Epoch 32/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3617 - acc: 0.8736
Epoch 33/50
22857/22857 [==============================] - 1s 35us/sample - loss: 0.3620 - acc: 0.8735
Epoch 34/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3616 - acc: 0.8732
Epoch 35/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3618 - acc: 0.8733
Epoch 36/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3613 - acc: 0.8737
Epoch 37/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3617 - acc: 0.8736
Epoch 38/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3615 - acc: 0.8738
Epoch 39/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3614 - acc: 0.8735
Epoch 40/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3613 - acc: 0.8737
Epoch 41/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3613 - acc: 0.8735
Epoch 42/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3613 - acc: 0.8735
Epoch 43/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3612 - acc: 0.8736
Epoch 44/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3611 - acc: 0.8740
Epoch 45/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3610 - acc: 0.8738
Epoch 46/50
22857/22857 [==============================] - 1s 35us/sample - loss: 0.3613 - acc: 0.8735
Epoch 47/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3612 - acc: 0.8740
Epoch 48/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3611 - acc: 0.8736
Epoch 49/50
22857/22857 [==============================] - 1s 32us/sample - loss: 0.3608 - acc: 0.8739
Epoch 50/50
22857/22857 [==============================] - 1s 33us/sample - loss: 0.3612 - acc: 0.8736
7620/7620 - 0s - loss: 0.3681 - acc: 0.8731
Loss: 0.3681099681090808, Accuracy: 0.8730971217155457

In [ ]:
# Predictive accuracy for both models is 87%
# Both models take similar amounts of time to train on the input data. 
# Biggest difference between the two models is implementation—the amount of code required to build and train the SVM is less than the comparable deep learning model. 
# As a result, many data scientists will prefer to use SVMs by default, then turn to deep learning models, as needed.